{% set name = "pathy" %}
{% set version = "0.10.2" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  - url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
    sha256: 79c572ab7fed84dc46837346edae58565992d0477a789cd4691a41d8eab9917d


build:
  number: 1
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps -vv
  entry_points:
    - pathy=pathy.cli:app

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6
    - smart_open >=5.0.0,<6.0.0
    - typer >=0.3.0,<1.0.0
    - dataclasses >=0.6,<1.0

test:
  imports:
    - {{ name }}
  requires:
    - pip
  commands:
    - pip check
    - pathy --help

about:
  home: https://github.com/justindujardin/pathy
  license: Apache-2.0
  license_file: LICENSE
  summary: A Path interface for local and cloud bucket storage
  description: |
    Pathy is a python package (with type annotations) for working with Bucket
    storage providers. It provides a CLI app for basic file operations between
    local files and remote buckets. It enables a smooth developer experience by
    supporting local file-system backed buckets during development and testing.
    It makes converting bucket blobs into local files a snap with optional
    local file caching of blobs.
  doc_url: https://github.com/justindujardin/pathy
  dev_url: https://github.com/justindujardin/pathy

extra:
  recipe-maintainers:
    - honnibal
    - ines
    - adrianeboyd
    - justindujardin
